website/views.py
from datetime import datetime, timedelta
from time import sleep as wait

from flask import Blueprint, render_template, request, flash, jsonify, make_response
from flask_login import login_required, current_user
from sqlalchemy.util.topological import sort

from .models import Note
from . import db
import json

views = Blueprint('views', __name__)


@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    if request.method == 'POST':
        try:
            first_date = datetime.strptime(request.form.get('first_date'), '%Y-%m-%d')
            second_date = datetime.strptime(request.form.get('second_date'), '%Y-%m-%d')
            name_work = str(request.form.get('name_work'))
        except:
            flash('Input data!', category='error')
        else:
            count_days = (second_date - first_date).days
            new_note = Note(first_date=first_date,
                            second_date=second_date,
                            user_id=current_user.id,
                            name_work=name_work,
                            count_days=count_days)
            db.session.add(new_note)
            db.session.commit()
            flash('Note added!', category='success')
    sorted_dates = db.session.query(Note).filter_by(user_id=current_user.id).all()
    for i, _ in enumerate(sorted_dates):
        for j in range(i+1, len(sorted_dates)):
            if sorted_dates[i].first_date.timetuple().tm_year == sorted_dates[j].first_date.timetuple().tm_year and\
            sorted_dates[i].first_date.timetuple().tm_mon == sorted_dates[j].first_date.timetuple().tm_mon or \
            abs(sorted_dates[i].first_date.timetuple().tm_mon - sorted_dates[j].first_date.timetuple().tm_mon) == 1 or\
            abs(sorted_dates[j].first_date.timetuple().tm_mon - sorted_dates[i].first_date.timetuple().tm_mon) == 1:
                if 0>sorted_dates[i].first_date.timetuple().tm_yday-sorted_dates[j].first_date.timetuple().tm_yday>-3:
                    sorted_dates[j].first_date = sorted_dates[i].first_date
                elif 3>sorted_dates[i].first_date.timetuple().tm_yday-sorted_dates[j].first_date.timetuple().tm_yday>0:
                    sorted_dates[i].first_date = sorted_dates[j].first_date

    for i, _ in enumerate(sorted_dates):
        for j in range(i, len(sorted_dates)):
            if sorted_dates[i].first_date.timetuple().tm_year == sorted_dates[j].second_date.timetuple().tm_year and \
            sorted_dates[i].first_date.timetuple().tm_mon == sorted_dates[j].second_date.timetuple().tm_mon or\
            abs(sorted_dates[i].first_date.timetuple().tm_mon - sorted_dates[j].second_date.timetuple().tm_mon) == 1 or\
            abs(sorted_dates[j].first_date.timetuple().tm_mon - sorted_dates[i].second_date.timetuple().tm_mon) == 1:
                wait(5)
                if -3 <sorted_dates[i].first_date.timetuple().tm_yday - sorted_dates[j].second_date.timetuple().tm_yday<0:
                    sorted_dates[j].second_date = sorted_dates[i].first_date
                elif -3<sorted_dates[j].first_date.timetuple().tm_yday - sorted_dates[i].second_date.timetuple().tm_yday<0:
                    sorted_dates[i].second_date = sorted_dates[j].first_date
                elif 0<sorted_dates[i].first_date.timetuple().tm_yday - sorted_dates[j].second_date.timetuple().tm_yday<3:
                    sorted_dates[i].first_date = sorted_dates[j].second_date
                elif 0<sorted_dates[j].first_date.timetuple().tm_yday - sorted_dates[i].second_date.timetuple().tm_yday<3:
                    sorted_dates[j].first_date = sorted_dates[i].second_date

    for i, _ in enumerate(sorted_dates):
        for j in range(i+1, len(sorted_dates)):
            if sorted_dates[i].second_date.timetuple().tm_year == sorted_dates[j].second_date.timetuple().tm_year and\
            sorted_dates[i].second_date.timetuple().tm_mon == sorted_dates[j].second_date.timetuple().tm_mon or \
            abs(sorted_dates[i].second_date.timetuple().tm_mon - sorted_dates[j].second_date.timetuple().tm_mon) == 1 or \
            abs(sorted_dates[j].second_date.timetuple().tm_mon - sorted_dates[i].second_date.timetuple().tm_mon) == 1:
                if 0>sorted_dates[i].second_date.timetuple().tm_yday-sorted_dates[j].second_date.timetuple().tm_yday>-3:
                    sorted_dates[j].second_date = sorted_dates[i].second_date
                elif 3>sorted_dates[i].second_date.timetuple().tm_yday-sorted_dates[j].second_date.timetuple().tm_yday>0:
                    sorted_dates[i].second_date=sorted_dates[j].second_date
    sorted_dates = db.session.query(Note).filter_by(user_id=current_user.id).all()
    sorted_first_dates = []
    sorted_second_dates = []
    dates_sorted = []
    for i, _ in enumerate(sorted_dates):
        sorted_first_dates.append(sorted_dates[i].first_date)
        sorted_second_dates.append(sorted_dates[i].second_date)
        dates_sorted.append(sorted_first_dates[i])
        dates_sorted.append(sorted_second_dates[i])
    dates_sorted = sorted(list(set(dates_sorted)))

    # stop_interval = []
    # for i, _ in enumerate(dates_sorted):
    #     if 0 < i < len(dates_sorted)-1:
    #         interval = dates_sorted[i] + timedelta(days=1)
    #         stop_interval.append(interval)

    interval_number = []
    for i in range(len(dates_sorted)-1):
        interval_number.append(i+1)

    return render_template("home.html",
                           user=current_user,
                           dates_sorted=dates_sorted, # {'dates_sorted': dates_sorted, 'stop_interval': stop_interval},
                           interval_number=interval_number)

@views.route('/print_intervals/<intervals>', methods=['GET', 'POST'])
@login_required
def installation(intervals):
    sorted_dates = db.session.query(Note).filter_by(user_id=current_user.id).all()
    for i, _ in enumerate(sorted_dates):
        for j in range(i + 1, len(sorted_dates)):
            if sorted_dates[i].first_date.timetuple().tm_year == sorted_dates[j].first_date.timetuple().tm_year and \
                    sorted_dates[i].first_date.timetuple().tm_mon == sorted_dates[j].first_date.timetuple().tm_mon or \
                    abs(sorted_dates[i].first_date.timetuple().tm_mon - sorted_dates[
                        j].first_date.timetuple().tm_mon) == 1 or \
                    abs(sorted_dates[j].first_date.timetuple().tm_mon - sorted_dates[
                        i].first_date.timetuple().tm_mon) == 1:
                if 0 > sorted_dates[i].first_date.timetuple().tm_yday - sorted_dates[
                    j].first_date.timetuple().tm_yday > -3:
                    sorted_dates[j].first_date = sorted_dates[i].first_date
                elif 3 > sorted_dates[i].first_date.timetuple().tm_yday - sorted_dates[
                    j].first_date.timetuple().tm_yday > 0:
                    sorted_dates[i].first_date = sorted_dates[j].first_date

    for i, _ in enumerate(sorted_dates):
        for j in range(i, len(sorted_dates)):
            if sorted_dates[i].first_date.timetuple().tm_year == sorted_dates[j].second_date.timetuple().tm_year and \
                    sorted_dates[i].first_date.timetuple().tm_mon == sorted_dates[j].second_date.timetuple().tm_mon or \
                    abs(sorted_dates[i].first_date.timetuple().tm_mon - sorted_dates[
                        j].second_date.timetuple().tm_mon) == 1 or \
                    abs(sorted_dates[j].first_date.timetuple().tm_mon - sorted_dates[
                        i].second_date.timetuple().tm_mon) == 1:
                wait(5)
                if -3 < sorted_dates[i].first_date.timetuple().tm_yday - sorted_dates[
                    j].second_date.timetuple().tm_yday < 0:
                    sorted_dates[j].second_date = sorted_dates[i].first_date
                elif -3 < sorted_dates[j].first_date.timetuple().tm_yday - sorted_dates[
                    i].second_date.timetuple().tm_yday < 0:
                    sorted_dates[i].second_date = sorted_dates[j].first_date
                elif 0 < sorted_dates[i].first_date.timetuple().tm_yday - sorted_dates[
                    j].second_date.timetuple().tm_yday < 3:
                    sorted_dates[i].first_date = sorted_dates[j].second_date
                elif 0 < sorted_dates[j].first_date.timetuple().tm_yday - sorted_dates[
                    i].second_date.timetuple().tm_yday < 3:
                    sorted_dates[j].first_date = sorted_dates[i].second_date

    for i, _ in enumerate(sorted_dates):
        for j in range(i + 1, len(sorted_dates)):
            if sorted_dates[i].second_date.timetuple().tm_year == sorted_dates[j].second_date.timetuple().tm_year and \
                    sorted_dates[i].second_date.timetuple().tm_mon == sorted_dates[j].second_date.timetuple().tm_mon or \
                    abs(sorted_dates[i].second_date.timetuple().tm_mon - sorted_dates[
                        j].second_date.timetuple().tm_mon) == 1 or \
                    abs(sorted_dates[j].second_date.timetuple().tm_mon - sorted_dates[
                        i].second_date.timetuple().tm_mon) == 1:
                if 0 > sorted_dates[i].second_date.timetuple().tm_yday - sorted_dates[
                    j].second_date.timetuple().tm_yday > -3:
                    sorted_dates[j].second_date = sorted_dates[i].second_date
                elif 3 > sorted_dates[i].second_date.timetuple().tm_yday - sorted_dates[
                    j].second_date.timetuple().tm_yday > 0:
                    sorted_dates[i].second_date = sorted_dates[j].second_date
    sorted_first_dates = []
    sorted_second_dates = []
    dates_sorted = []
    for i, _ in enumerate(sorted_dates):
        sorted_first_dates.append(sorted_dates[i].first_date)
        sorted_second_dates.append(sorted_dates[i].second_date)
        dates_sorted.append(sorted_first_dates[i])
        dates_sorted.append(sorted_second_dates[i])
    dates_sorted = sorted(list(set(dates_sorted)))

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
  </body>
</html>

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content %}

<h1 align="center">Intervals</h1>
<div class="table_intervals" style="position: relative;top: 25px;width: 320px;left: 400px;height: 32px;">
    <label class="line" style="position: relative;top: 58px;left: 0px;border: 1px solid #4f4f4f;width: 410px;"></label>
    <table style="width: 435px;">

        <thead style="position: relative; bottom: 85px;">
            <tr>
                <th style="width: 74px;position: absolute;top: 100px;">№</th>
                <th style="width: 74px;position: absolute;top: 100px;left: 30px;">First date</th>
                <th style="width: 110px;position: absolute;top: 100px;left: 120px;">Second date</th>
                <th style="width: 100px;position: absolute;top: 100px; left: 220px;">Name work</th>
                <th style="width: 100px;position: absolute;top: 100px; left: 320px;">Count days</th>
                <th style="width: 32px;position: absolute;top: 127px; left: 410px;"></th>
            </tr>
        </thead>

        <tbody style="position:relative; top: 50px;">
        {% for note in user.notes %}
            <tr>
                <td style="padding: 0px 5px 0px 0px;">{{ note.id }}</td>
                <td style="width: 100px;position: relative;right: 27px;">{{ note.first_date }}</td>
                <td style="width: 98px;position: relative;right: 33px;">{{ note.second_date }}</td>
                <td>{{ note.name_work }}</td>
                <td style="width: 98px;position: relative;left: 15px;">{{ note.count_days }}</td>
                <td style="width: 16px;"><button type="button" class="close" onClick="deleteNote({{ note.id }})">
                          <span aria-hidden="true">&times;</span>
                    </button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<form method="POST" action="{{ url_for('views.home') }}">
    <label class="intervals"
           style="font-weight: bold; position: relative; top: 10px;">Add intervals:</label>
    <label class="first_date"
           style="position: relative; top: 35px; right: 94px">Add first date:</label>
    <label class="second_date"
           style="position: relative; top: 76px; right: 198px">Add second date:</label>
    <labelпге class="name_work"
           style="position: relative; top: 117px; right: 326px">Add work name:</labelпге>
    <input type="date" name="first_date" id="note_first_date" class="form-control"
           style="position: relative; width: 200px; left: 150px" >
    <input type="date" name="second_date" id="note_second_date" class="form-control"
           style="position: relative; width: 200px; left: 150px">
    <input type="text" name="name_work" id="note_name_work" placeholder="name work" class="form-control"
           style="position: relative; width: 200px; left: 150px">
    <button type="submit" style="position: relative; top: 10px;" class="btn btn-primary">Input intervals</button>
</form>

<div class="line_intervals3" style="height: 1px;width: 30px;
border: 1px solid black;position: relative;left: 900px;bottom: 130px;"></div>

<div  style="position: relative; bottom: 130px; left: 890px; width: 50px; height: 50px">
    {% for number in interval_number %}
        <div id="line_intervals" style="height: 50px; width: 1px; border: 1px solid black; position: relative;
        left: 25px; bottom: 2px;">
            <a style="  position: relative; right: 15px; top: 10px;">{{ number }}</a>
        </div>
        <div class="line_intervals2" style="height: 1px; width: 30px; border: 1px solid black; position: relative;
        left: 10px; bottom: 4px;"></div>
    {% endfor %}
</div>

{% for date in dates_sorted %}
    <div style="position: relative; left: 935px; bottom: 195px">
        <div style="position: relative; height: 50px;">{{ date }}</div>
    </div>
{% endfor %}

{% if interval_number == [] %}
<a style="font-weight: bold; position: relative; color: red">ADD intervals!!!</a>
{% else %}
<button><a class="nav-item nav-link" id="print" href="{{ url_for('views.installation', intervals=interval_number) }}">Confirm</a></button>
{% endif %}

{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content %}
<form method="POST">
  <h3 align="center">Login</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Enter password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/print_intervals.html
<div id="options">

    <h1 align="center">Protocol</h1>

    <div class="table_intervals" style="position: relative;top: 57px;width: 330px;left: 655px;">
        <label class="line" style="position: relative;display: inline-block;top: 45px;left: 0px;border: 1px solid #4f4f4f;width: 210px;"></label>
        <table style="width: 250px;">
            <thead style="position: relative; bottom: 85px;">
                <tr>
                    <th style="width: 100px;position: absolute;top: 100px;left:20px;">Name work</th>
                    <th style="width: 74px;position: absolute;top: 100px; left: 125px;">Intersvals</th>
                </tr>
            </thead>
            <tbody style="position:relative; top: 50px;">
            {% for note in user %}
{#                {{ note }}#}

    {#             user.notes #}
                <tr>
                    <td style="width: 100px;position: relative;right: 0px;">data.dates_sorted </td>
                    <td> {{ note }} </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="table_intervals" style="position: relative;bottom: 25px;width: 320px;left: 100px;height: 32px;">
        <label class="line" style="position: relative;display: inline-block;top: 45px;left: 0px;border: 1px solid #4f4f4f;width: 410px;"></label>
        <table style="width: 435px;">
            <thead style="position: relative; bottom: 85px;">
                <tr>
                    <th style="width: 74px;position: absolute;top: 100px; right: 390px;">№</th>
                    <th style="width: 74px;position: absolute;top: 100px;left: 30px;">First date</th>
                    <th style="width: 110px;position: absolute;top: 100px;left: 112px;">Second date</th>
                    <th style="width: 100px;position: absolute;top: 100px; left: 220px;">Name work</th>
                    <th style="width: 100px;position: absolute;top: 100px; left: 320px;">Count days</th>
                </tr>
            </thead>
            <tbody style="position:relative; top: 50px;">
            {% for note in user.current_user.notes %}
                <tr>
                    <td style="padding: 0px 5px 0px 0px;">{{ note.id }}</td>
                    <td style="width: 100px;position: relative;right: 27px;">{{ note.first_date }}</td>
                    <td style="width: 98px;position: relative;right: 33px;">{{ note.second_date }}</td>
                    <td>{{ note.name_work }}</td>
                    <td style="width: 98px;position: relative;left: 15px;">{{ note.count_days }}</td>
                        </button>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>



    <div class="line_intervals3" style="display: inline-block; height: 0px; width: 30px;
    border: 1px solid black; position: relative; left: 1100px; top: 5px;"></div>

    <div  style="position: relative; top: 5px; left: 1090px; width: 50px; height: 50px">
        {% for number in dates_sorted.intervals %}
            <div id="line_intervals" style="height: 49px; width: 0px; border: 1px solid black; position: relative;
            left: 25px; bottom: 0px;">
                <a style="  position: relative; right: 15px; top: 10px;">{{ number }}</a>
            </div>
            <div class="line_intervals2" style="height: 0px; width: 30px; border: 1px solid black; position: relative;
            left: 10px; bottom: 0px;"></div>
        {% endfor %}
    </div>

    {% for date in dates_sorted.dates_sorted %}
         <div  style="position: relative; bottom: 35px; left: 1110px;">
            <div style="position: relative; height: 50px;">
                <div style="position: relative; bottom: 10px; left: 30px">{{ date }}</div>
            </div>
         </div>
    {% endfor %}
</div>

<input id="printpagebutton" type="button" value="print news" onclick="printpage()"/>

<script>
    function printpage() {
        //Get the print button and put it into a variable
        var printButton = document.getElementById("printpagebutton");
        //Set the print button visibility to 'hidden'
        printButton.style.visibility = 'hidden';
        //Print the page content
        window.print()
        printButton.style.visibility = 'visible';
    }
</script>

<style>
    #options {
	align-content:center;
	align-items:center;
    text-align: center;
}
</style>

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
content %}
<form method="POST">
  <h3 align="center">Sign Up</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="firstName">First Name</label>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      placeholder="Enter first name"
    />
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <label for="password2">Password (Confirm)</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}